version: '3.8'

services:
  roo-code-server:
    image: codercom/code-server:latest
    container_name: roo-code-server
    ports:
      - "${CODE_SERVER_PORT:-8080}:8080"
    volumes:
      - ./workspace:/home/coder/workspace
      - /tmp:/tmp
      - ~/.config/code-server:/home/coder/.config/code-server
    environment:
      - ROO_CODE_IPC_SOCKET_PATH=/tmp/roo-code-ipc.sock
      - PASSWORD=${CODE_SERVER_PASSWORD:-roo-blessed-demo}
      - SUDO_PASSWORD=${SUDO_PASSWORD:-roo-blessed-demo}
    command: >
      code-server
      --bind-addr 0.0.0.0:8080
      --auth password
      /home/coder/workspace
    restart: unless-stopped
    user: "1000:1000"
    
  # Optional: Roo Blessed client in a separate container
  roo-blessed-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: roo-blessed-client
    depends_on:
      - roo-code-server
    volumes:
      - /tmp:/tmp
    environment:
      - ROO_CODE_IPC_SOCKET_PATH=/tmp/roo-code-ipc.sock
    stdin_open: true
    tty: true
    profiles:
      - client